
#libapp_connected_applib-objs +=src/system/AmbaShell_AmbaLink.o
libapplib-objs +=src/system/ApplibSys_Gyro.o
libapplib-objs +=src/system/ApplibSys_Lcd.o
libapplib-objs +=src/system/ApplibSys_Lens.o
libapplib-objs +=src/system/ApplibSys_Sensor.o
libapplib-objs +=src/system/ApplibSys_Vin.o
libapplib-objs +=src/system/ApplibSys_Vout.o
libapplib-objs +=src/system/ApplibSys_Gps.o
libapplib-objs +=src/system/ApplibSys_GSensor.o