
libapplib-objs +=src/comsvc/ApplibComSvc_AsyncOp.o
libapplib-objs +=src/comsvc/ApplibComSvc_Hcmgr.o
libapplib-objs +=src/comsvc/ApplibComSvc_MemMgr.o
libapplib-objs +=src/comsvc/ApplibComSvc_Timer.o

