/**
  * @file src/app/apps/flow/widget/dialog/connectedcam/dialog_table.h
  *
  *  Header of Dialog table
  *
  * History:
  *    2013/11/22 - [Martin Lai] created file
  *
  *
 * Copyright (c) 2015 Ambarella, Inc.
 *
 * This file and its contents (¡°Software¡±) are protected by intellectual property rights
 * including, without limitation, U.S. and/or foreign copyrights.  This Software is also the
 * confidential and proprietary information of Ambarella, Inc. and its licensors.  You may
 * not use, reproduce, disclose, distribute, modify, or otherwise prepare derivative
 * works of this Software or any portion thereof except pursuant to a signed license
 * agreement or nondisclosure agreement with Ambarella, Inc. or its authorized
 * affiliates.	In the absence of such an agreement, you agree to promptly notify and
 * return this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-
 * INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR
 * MALFUNCTION; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  */
#ifndef APP_WIDGET_DIALOG_TABLE_H_
#define APP_WIDGET_DIALOG_TABLE_H_

__BEGIN_C_PROTO__

enum dialog_subject_id_e {
    DIALOG_SUB_DEL = 0,
    DIALOG_SUB_DEL_ALL,
    DIALOG_SUB_MVRECOVER_YES_OR_NO,
    DIALOG_SUB_MVRECOVER_OK,
    DIALOG_SUB_MVRECOVER_FAIL,
    DIALOG_SUB_FWUPDATE_YES_OR_NO,
    DIALOG_SUB_FWUPDATE_OK,
    DIALOG_SUB_FWUPDATE_FAILED,
    DIALOG_SUB_CALIBUPDATE_YES_OR_NO,
    DIALOG_SUB_CALIBUPDATE_OK,
    DIALOG_SUB_CALIBUPDATE_FAILED,
    DIALOG_SUB_FORMAT_CARD_YES_OR_NO,
    DIALOG_SUB_FORMAT_CARD_CAUTION,
    DIALOG_SUB_FORMAT_CARD_NO_OPTIMUM,
    DIALOG_SUB_FORMAT_CARD_UNKNOWN,
    DIALOG_SUB_FORMAT_CARD_FAILED,
    DIALOG_SUB_FORMAT_CARD_OK,
    DIALOG_SUB_DEFAULT_SETTING_YES_OR_NO,
    DIALOG_SUB_DEFAULT_SETTING_REBOOT,
    DIALOG_SUB_PHOTO_ROTATE_SAVE,
    DIALOG_SUB_RED_EYE_REMOVAL,
    DIALOG_SUB_DYNAMIC_LIGHTING,
    DIALOG_SUB_CROP,
    DIALOG_SUB_PARTIAL_DEL,
    DIALOG_SUB_DIVIDE,
    DIALOG_SUB_MERGE,
    DIALOG_SUB_DONE,
    DIALOG_SUB_FAIL,
    DIALOG_SUB_LIST_FULL,
    DIALOG_SUB_DISK_FULL,
    DIALOG_SUB_UNKNOWN_FORMAT,
    DIALOG_SUB_ILLEGAL_INTERVAL,
    DIALOG_SUB_WRONG_RESOLUTION,
    DIALOG_SUB_MEDIA_TYPE_MISMATCH,
    DIALOG_SUB_VIDEO_MISMATCH,
    DIALOG_SUB_AUDIO_MISMATCH,
    DIALOG_SUB_FUNC_NOT_AVAILABLE,
    DIALOG_SUB_NO_ORIENTATION,
    DIALOG_SUB_PLIST_ADD_FILE_YES_OR_NO,
    DIALOG_SUB_PLIST_ADD_FILE_SUCCESS,
    DIALOG_SUB_PLIST_ADD_FILE_FAIL,
    DIALOG_SUB_PLIST_ADD_CLR_PICKUP_FILE_YES_OR_NO,
    DIALOG_SUB_UPLOAD_YES_OR_NO,
    DIALOG_SUB_UPLOAD_TIME_OUT,
    DIALOG_SUB_UNSUPPORT_FORMAT,
    DIALOG_SUB_NUM
};

extern UINT32 dialog_subject_str_tbl[DIALOG_SUB_NUM];

__END_C_PROTO__

#endif /* APP_WIDGET_DIALOG_TABLE_H_ */
