
include $(srctree)/app/cardv/app/apps/gui/misc/Makefile
include $(srctree)/app/cardv/app/apps/gui/pb/Makefile
include $(srctree)/app/cardv/app/apps/gui/rec/Makefile
include $(srctree)/app/cardv/app/apps/gui/resource/Makefile
include $(srctree)/app/cardv/app/apps/gui/thumb/Makefile
include $(srctree)/app/cardv/app/apps/gui/usb/Makefile
include $(srctree)/app/cardv/app/apps/gui/utility/Makefile
include $(srctree)/app/cardv/app/apps/gui/widget/Makefile
include $(srctree)/app/cardv/app/apps/gui/sound/Makefile
