obj-y += libapplib.a

# Link script

ccflags-y := -I$(srctree)/vendors/ambarella/inc/ssp
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/link
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/link/rpcprog
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/soc
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/threadx
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/rpcprog
ccflags-y += -I$(srctree)/vendors/foss/gps
ccflags-y += -I$(srctree)/vendors/ecladas
ccflags-y += -I$(srctree)/vendors/foss/freetype
ccflags-y += -I$(srctree)/vendors/foss/freetype/freetype-2.4.11/include
ccflags-y += -I$(srctree)/vendors/foss/freetype/freetype-2.4.11/include/freetype
ccflags-y += -I$(srctree)/peripheral/misc/inc
ccflags-y += -I$(srctree)/peripheral/sensor/inc
ccflags-y += -I$(srctree)/peripheral/lcd/inc
ccflags-y += -I$(srctree)/peripheral/yuvinput/inc
ccflags-y += -I$(srctree)/peripheral/gps/inc
ccflags-y += -I$(srctree)/peripheral/g_sensor/inc
ccflags-y += -I$(srctree)/vendors/ambarella/inc/comsvc/AmbaSys
ccflags-y += -I$(srctree)/vendors/ambarella/inc/comsvc/AmbaShell
ccflags-y += -I$(srctree)/vendors/ambarella/inc/comsvc/AmbaTest
ccflags-y += -I$(srctree)/vendors/ambarella/inc/comsvc/misc
ccflags-y += -I$(srctree)/vendors/ambarella/inc/comsvc/tune
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/soc
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/dsp
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/fs
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/prfile2
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/threadx
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/rpcprog
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/usb
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/usb/usbx
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/usb/usbx/usbx_host_controllers
ccflags-y += -I$(srctree)/vendors/ambarella/inc/ssp/usb/usbx/usbx_host_classes
ccflags-y += -I$(srctree)/vendors/ambarella/inc/mw
ccflags-y += -I$(srctree)/vendors/ambarella/inc/mw/net/rpcprog
ccflags-y += -I$(srctree)/vendors/ambarella/inc
ccflags-y += -I$(srctree)/vendors/ambarella/inc/image
ccflags-y += -I$(srctree)/vendors/ambarella/inc/image/ituner
ccflags-y += -I$(srctree)/vendors/ambarella/inc/va
ccflags-y += -I$(srctree)/app/cardv/applib/inc


libapplib-objs :=

include $(srctree)/app/cardv/applib/src/Makefile


install-files := libapplib.a
