
#libapplib-objs +=src/transcoder/decode_utility/ApplibTranscoder_Common.o
#libapplib-objs +=src/transcoder/decode_utility/ApplibTranscoder_Internal.o
#libapplib-objs +=src/transcoder/decode_utility/ApplibTranscoder_StillTask.o
libapplib-objs +=src/transcoder/decode_utility/ApplibTranscoder_VideoTask.o
