
libapp-objs +=apps/flow/rec/rec_cam.o
libapp-objs +=apps/flow/rec/rec_cam_func.o
libapp-objs +=apps/flow/rec/rec_cam_op.o

ifeq ($(CONFIG_APP_AMBA_LINK),y)
libapp-objs +=apps/flow/rec/rec_cam_netctrl.o
endif
