

include $(srctree)/app/cardv/applib/src/graphics/bmp/Makefile
include $(srctree)/app/cardv/applib/src/graphics/font/Makefile
include $(srctree)/app/cardv/applib/src/graphics/BMPfont/Makefile
include $(srctree)/app/cardv/applib/src/graphics/FTfont/Makefile
include $(srctree)/app/cardv/applib/src/graphics/canvas/Makefile

include $(srctree)/app/cardv/applib/src/graphics/obj/Makefile
include $(srctree)/app/cardv/applib/src/graphics/render/Makefile
include $(srctree)/app/cardv/applib/src/graphics/shape/Makefile
include $(srctree)/app/cardv/applib/src/graphics/stamp/Makefile
include $(srctree)/app/cardv/applib/src/graphics/string/Makefile
include $(srctree)/app/cardv/applib/src/graphics/UIobj/Makefile
include $(srctree)/app/cardv/applib/src/graphics/DirectDraw/Makefile

libapplib-objs +=src/graphics/ApplibGraphics_Common.o
libapplib-objs +=src/graphics/ApplibGraphics.o

