

libapp-objs +=apps/flow/widget/widgetmgt.o

include $(srctree)/app/cardv/app/apps/flow/widget/dialog/Makefile
include $(srctree)/app/cardv/app/apps/flow/widget/menu/Makefile
include $(srctree)/app/cardv/app/apps/flow/widget/info_prompt/Makefile
