
libapplib-objs +=src/va/ApplibVideoAnal_StmpHdlr.o
libapplib-objs +=src/va/ApplibVideoAnal_FrmHdlr.o
libapplib-objs +=src/va/ApplibVideoAnal_3aHdlr.o
libapplib-objs +=src/va/ApplibVideoAnal_ADAS.o
libapplib-objs +=src/va/ApplibVideoAnal_FCMD.o
libapplib-objs +=src/va/ApplibVideoAnal_LLWS.o
libapplib-objs +=src/va/ApplibVideoAnal_MD.o
libapplib-objs +=src/va/ApplibVideo_Ecl_ADAS.o
