
libapplib-objs +=src/player/decode_utility/ApplibPlayer_Common.o
libapplib-objs +=src/player/decode_utility/ApplibPlayer_Internal.o
libapplib-objs +=src/player/decode_utility/ApplibPlayer_StillTask.o
libapplib-objs +=src/player/decode_utility/ApplibPlayer_VideoTask.o
