
include $(srctree)/app/cardv/applib/src/monitor/TimerBasedMonitor/Makefile

libapplib-objs +=src/monitor/ApplibMonitor.o
libapplib-objs +=src/monitor/ApplibMonitor_HDMI.o
libapplib-objs +=src/monitor/ApplibMonitor_Storage.o
