
libapp-objs +=apps/gui/pb/gui_pb_multi.o
libapp-objs +=apps/gui/pb/gui_pb_photo.o
libapp-objs +=apps/gui/pb/gui_pb_video.o
libapp-objs +=apps/gui/pb/gui_pb_sound.o
libapp-objs +=apps/gui/pb/gui_hdmi_test.o