

include $(srctree)/app/cardv/applib/src/transcoder/decode_utility/Makefile
include $(srctree)/app/cardv/applib/src/transcoder/still_decode/Makefile
include $(srctree)/app/cardv/applib/src/transcoder/video_decode/Makefile
