
libapplib-objs +=src/net/ApplibNet_Base.o
libapplib-objs +=src/net/ApplibNet_Control.o
libapplib-objs +=src/net/ApplibNet_Fifo.o
libapplib-objs +=src/net/ApplibNet_IPCTest.o
libapplib-objs +=src/net/ApplibNet_JsonUtility.o
libapplib-objs +=src/net/ApplibNet_HiberTest.o
