/**
  * @file src/app/apps/flow/widget/menu/connectedcam/menu_setup.h
  *
  * Header of Setup-related Menu Items
  *
  * History:
  *    2013/11/22 - [Martin Lai] created file
  *
  *
 * Copyright (c) 2015 Ambarella, Inc.
 *
 * This file and its contents (¡°Software¡±) are protected by intellectual property rights
 * including, without limitation, U.S. and/or foreign copyrights.  This Software is also the
 * confidential and proprietary information of Ambarella, Inc. and its licensors.  You may
 * not use, reproduce, disclose, distribute, modify, or otherwise prepare derivative
 * works of this Software or any portion thereof except pursuant to a signed license
 * agreement or nondisclosure agreement with Ambarella, Inc. or its authorized
 * affiliates.	In the absence of such an agreement, you agree to promptly notify and
 * return this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-
 * INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR
 * MALFUNCTION; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  */
#ifndef APP_WIDGET_MENU_SETUP_H_
#define APP_WIDGET_MENU_SETUP_H_


__BEGIN_C_PROTO__

/*************************************************************************
 * setup menu definitions
 ************************************************************************/
typedef enum _MENU_SETUP_ITEM_ID_e_ {
#ifdef CONFIG_APP_ARD
    MENU_SETUP_LANGUAGE,
#endif
    MENU_SETUP_SYSTEM_TYPE,
    MENU_SETUP_DMF_MODE,
    MENU_SETUP_DRIVER_ID_SETUP,
    MENU_SETUP_TIME,
#ifdef CONFIG_APP_ARD
    MENU_SETUP_STAMP_CHOOSE,
#endif
    MENU_SETUP_DATE_TIME_DISPLAY,
    MENU_SETUP_FORMAT,
    MENU_SETUP_DEFAULT,
    MENU_SETUP_LCD_CONTROL,
    MENU_SETUP_POWEROFF,
    MENU_SETUP_POWERSAVING,
#ifdef CONFIG_APP_ARD
    MENU_SETUP_DELAY_POWER_OFF,
#endif
    MENU_SETUP_HDMI,
    MENU_SETUP_FLASHLIGHT,
    MENU_SETUP_USB_MODE,
    MENU_SETUP_INPUT_DIMENSION_MODE,
#ifdef CONFIG_APP_ARD
    MENU_SETUP_INPUT_NEAR_FAR,
    MENU_SETUP_AUDIO_VOLUME,
#endif
    MENU_SETUP_OUTPUT_DIMENSION_MODE,
    MENU_SETUP_WIFI,
    MENU_SETUP_WIFI_CONFIG,
#ifdef CONFIG_APP_ARD
    MENU_SETUP_RECORD_MODE,
    MENU_SETUP_CARD_VOLUME,
    MENU_SETUP_BEEP_SOUND,
    MENU_SETUP_BACKLIGHT_AUTO,
    MENU_SETUP_VERSION,
#endif
    MENU_SETUP_ITEM_NUM
} MENU_SETUP_ITEM_ID_e;

#ifdef CONFIG_ECL_GUI
typedef enum _MENU_ECL_SETTING_e_ {
   MENU_FIRST_SEL = 0,
   MENU_SECOND_SEL,
   MENU_THIRD_SEL,   
   MENU_FOUR_SEL,
   MENU_FIVE_SEL,
   MENU_SIX_SEL,
   MENU_SEVEN_SEL,   
   MENU_EIGHT_SEL,
   MENU_NINE_SEL, 
   MENU_TEN_SEL,
   MENU_SEL_NUM,   
} MENU_ECL_SETTING_e;

typedef enum _MENU_ECL_SETUP_ITEM_ID_e_ {
   menu_adas_cali_item_start = 0,	
   menu_chinese,
   menu_english,
   menu_default,
   menu_ecl_num
} MENU_ECL_SETUP_ITEM_ID_e;

typedef enum _MENU_FUNC_SETUP_ITEM_ID_e_ {
   menu_font_car_alarm = 0,
   menu_change_road,	 	
   menu_keep_dis,
   menu_start_alarm,
} MENU_FUNC_SETUP_ITEM_ID_e;

typedef enum _MENU_ALARM_SETUP_ITEM_ID_e_ {
   menu_alarm_near = 0,
   menu_alarm_middle,
   menu_alarm_far,   
} MENU_ALARM_SETUP_ITEM_ID_e;

typedef enum _MENU_ECL_RECORDER_ITEM_ID_e_ {
   MENU_CARD_FORMAT,
   MENU_TIME_SET,
   MENU_LANGUAGE_SET,   
   MENU_MOTION_DAT,
   MENU_GSENSOR,
   MENU_SPLIT_REC,
   MENU_FLICKER,
   MENU_BACKLIGHT,
   MENU_PARKING_CON,
   MENU_RECORD_NUM
} MENU_ECL_RECORDER_ITEM_ID_e;	

#endif

typedef enum _MENU_SETUP_SYSTEM_TYPE_SEL_ID_e_ {
    MENU_SETUP_SYSTEM_TYPE_NTSC = 0,
    MENU_SETUP_SYSTEM_TYPE_PAL,
    MENU_SETUP_SYSTEM_TYPE_SEL_NUM
} MENU_SETUP_SYSTEM_TYPE_SEL_ID_e;

typedef enum _MENU_SETUP_DMF_MODE_SEL_ID_e_ {
    MENU_SETUP_DMF_MODE_RESET = 0,
    MENU_SETUP_DMF_MODE_SERIAL,
    MENU_SETUP_DMF_MODE_SEL_NUM
} MENU_SETUP_DMF_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_TIME_SEL_ID_e_ {
    MENU_SETUP_TIME_YEAR = 0,
    MENU_SETUP_TIME_MONTH,
    MENU_SETUP_TIME_DAY,
    MENU_SETUP_TIME_HOUR,
    MENU_SETUP_TIME_MINUTE,
    MENU_SETUP_TIME_SEL_NUM
} MENU_SETUP_TIME_SEL_ID_e;

typedef enum _MENU_SETUP_DATE_TIME_DISPLAY_SEL_ID_e_ {
    MENU_SETUP_DATE_TIME_DISPLAY_OFF = 0,
    MENU_SETUP_DATE_TIME_DISPLAY_DATE,
    MENU_SETUP_DATE_TIME_DISPLAY_TIME,
    MENU_SETUP_DATE_TIME_DISPLAY_BOTH,
    MENU_SETUP_DATE_TIME_DISPLAY_SEL_NUM
} MENU_SETUP_DATE_TIME_DISPLAY_SEL_ID_e;

typedef enum _MENU_SETUP_LCD_CTRL_SEL_ID_e_ {
    MENU_SETUP_LCD_CONTROL_BRIGHTNESS = 0,
    MENU_SETUP_LCD_CONTROL_CONTRAST,
    MENU_SETUP_LCD_CONTROL_COLOR_BALANCE,
    MENU_SETUP_LCD_CONTROL_SEL_NUM
} MENU_SETUP_LCD_CTRL_SEL_ID_e;

typedef enum _MENU_SETUP_POWEROFF_SEL_ID_e_ {
    MENU_SETUP_POWEROFF_OFF = 0,
#ifdef CONFIG_APP_ARD
    MENU_SETUP_POWEROFF_1M,
#endif
    MENU_SETUP_POWEROFF_3M,
    MENU_SETUP_POWEROFF_5M,
    MENU_SETUP_POWEROFF_SEL_NUM
} MENU_SETUP_POWEROFF_SEL_ID_e;

typedef enum _MENU_SETUP_POWERSAVING_SEL_ID_e_ {
    MENU_SETUP_POWERSAVING_OFF = 0,
    MENU_SETUP_POWERSAVING_ON,
    MENU_SETUP_POWERSAVING_SEL_NUM
} MENU_SETUP_POWERSAVING_SEL_ID_e;

#ifdef CONFIG_APP_ARD
typedef enum _MENU_SETUP_DELAY_POWER_OFF_SEL_ID_e_ {
    MENU_SETUP_DELAY_POWER_OFF_CLOSE = 0,
    MENU_SETUP_DELAY_POWER_OFF_3_S,
    MENU_SETUP_DELAY_POWER_OFF_5_S,
    MENU_SETUP_DELAY_POWER_OFF_10_S,
    MENU_SETUP_DELAY_POWER_OFF_15_S,
    MENU_SETUP_DELAY_POWER_OFF_SEL_NUM
} MENU_SETUP_DELAY_POWER_OFF_SEL_ID_e;
#endif

typedef enum _MENU_SETUP_HDMI_FUNC_SEL_ID_e_ {
    MENU_SETUP_HDMI_OFF = 0,
    MENU_SETUP_HDMI_ON,
    MENU_SETUP_HDMI_SEL_NUM
} MENU_SETUP_HDMI_FUNC_SEL_ID_e;

typedef enum _MENU_SETUP_FLASHLIGHT_SEL_ID_e_ {
    MENU_SETUP_FLASHLIGHT_OFF = 0,
    MENU_SETUP_FLASHLIGHT_ON,
    MENU_SETUP_FLASHLIGHT_AUTO,
    MENU_SETUP_FLASHLIGHT_SEL_NUM
} MENU_SETUP_FLASHLIGHT_SEL_ID_e;

typedef enum _MENU_SETUP_USB_MODE_SEL_ID_e_ {
    MENU_SETUP_USB_MODE_MSC = 0,
    MENU_SETUP_USB_MODE_AMAGE,
    MENU_SETUP_USB_MODE_SEL_NUM
} MENU_SETUP_USB_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_INPUT_DIMENSION_MODE_SEL_ID_e_ {
    MENU_SETUP_INPUT_2D_R = 0,
    MENU_SETUP_INPUT_2D_L,
    MENU_SETUP_INPUT_3D,
    MENU_SETUP_INPUT_DIMENSION_MODE_SEL_NUM
} MENU_SETUP_INPUT_DIMENSION_MODE_SEL_ID_e;

#ifdef CONFIG_APP_ARD
typedef enum _MENU_SETUP_INPUT_NEAR_FAR_SEL_ID_e_ {
    MENU_SETUP_INPUT_NEAR = 0,
    MENU_SETUP_INPUT_FAR,
    MENU_SETUP_INPUT_NEAR_FAR_SEL_NUM
} MENU_SETUP_INPUT_NEAR_FAR_SEL_ID_e;
#endif

typedef enum _MENU_SETUP_OUTPUT_DIMENSION_MODE_SEL_ID_e_ {
    MENU_SETUP_OUTPUT_2D = 0,
    MENU_SETUP_OUTPUT_2D_RIGHT,
    MENU_SETUP_OUTPUT_2D_LEFT,
    MENU_SETUP_OUTPUT_3D,
    MENU_SETUP_OUTPUT_DIMENSION_MODE_SEL_NUM
} MENU_SETUP_OUTPUT_DIMENSION_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_WIFI_SEL_ID_e_ {
    MENU_SETUP_WIFI_OFF = 0,
    MENU_SETUP_WIFI_ON,
    MENU_SETUP_WIFI_ON_AP,
    MENU_SETUP_WIFI_SEL_NUM
} MENU_SETUP_WIFI_SEL_ID_e;

typedef enum _MENU_SETUP_WIFI_CONFIG_SEL_ID_e_ {
    MENU_SETUP_WIFI_CONFIG_0 = 0,
    MENU_SETUP_WIFI_CONFIG_1,
    MENU_SETUP_WIFI_CONFIG_2,
    MENU_SETUP_WIFI_CONFIG_3,
    MENU_SETUP_WIFI_CONFIG_4,
    MENU_SETUP_WIFI_CONFIG_SEL_NUM
} MENU_SETUP_WIFI_CONFIG_SEL_ID_e;
#ifdef CONFIG_APP_ARD
typedef enum _MENU_SETUP_LANGUAGE_SEL_ID_e_ {
    MENU_SETUP_LANGUAGE_ENGLISH = 0,
    MENU_SETUP_LANGUAGE_CHINESE_SIMPLIFIED,		
    MENU_SETUP_LANGUAGE_SEL_NUM
} MENU_SETUP_LANGUAGE_SEL_ID_e;

typedef enum _MENU_SETUP_RECORD_MODE_SEL_ID_e_ {
    MENU_SETUP_RECORD_MODE_AUTO = 0,
    MENU_SETUP_RECORD_MODE_MANUAL,
    MENU_SETUP_RECORD_MODE_SEL_NUM
} MENU_SETUP_RECORD_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_BEEP_SOUND_SEL_ID_e_ {
    MENU_SETUP_BEEP_SOUND_ON = 0,
    MENU_SETUP_BEEP_SOUND_OFF,
    MENU_SETUP_BEEP_SOUND_SEL_NUM
} MENU_SETUP_BEEP_SOUND_SEL_ID_e;

typedef enum _MENU_SETUP_BACKLIGHT_SEL_ID_e_ {
    MENU_SETUP_BACKLIGHT_AUTO_OFF = 0,
    MENU_SETUP_BACKLIGHT_AUTO_MIN_1,
    MENU_SETUP_BACKLIGHT_AUTO_MIN_3,
    MENU_SETUP_BACKLIGHT_AUTO_MIN_5,
    MENU_SETUP_BACKLIGHT_AUTO_SEL_NUM,
} MENU_SETUP_BACKLIGHT_SEL_ID_e;

typedef enum _MENU_SETUP_STAMP_CHOOSE_SEL_ID_E_ {
    MENU_SETUP_STAMP_CHOOSE_DATE = 0,
    MENU_SETUP_STAMP_CHOOSE_TIME,
    MENU_SETUP_STAMP_CHOOSE_DRIVERID,
    MENU_SETUP_STAMP_CHOOSE_NUM,
} MENU_SETUP_STAMP_CHOOSE_SEL_ID_e;

#endif
__END_C_PROTO__

#endif /* APP_WIDGET_MENU_SETUP_H_ */
