/**
  * @file src/app/apps/flow/widget/menu/connectedcam/menu_photo.h
  *
  * Header of Photo-related Menu Items
  *
  * History:
  *    2013/11/22 - [Martin Lai] created file
  *
  *
 * Copyright (c) 2015 Ambarella, Inc.
 *
 * This file and its contents (¡°Software¡±) are protected by intellectual property rights
 * including, without limitation, U.S. and/or foreign copyrights.  This Software is also the
 * confidential and proprietary information of Ambarella, Inc. and its licensors.  You may
 * not use, reproduce, disclose, distribute, modify, or otherwise prepare derivative
 * works of this Software or any portion thereof except pursuant to a signed license
 * agreement or nondisclosure agreement with Ambarella, Inc. or its authorized
 * affiliates.	In the absence of such an agreement, you agree to promptly notify and
 * return this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-
 * INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR
 * MALFUNCTION; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  */
#ifndef APP_WIDGET_MENU_PHOTO_H_
#define APP_WIDGET_MENU_PHOTO_H_

__BEGIN_C_PROTO__

/*************************************************************************
 * photo menu definitions
 ************************************************************************/
typedef enum _MENU_PHOTO_ITEM_ID_e_ {
    MENU_PHOTO_MULTI_CAP = 0,
    MENU_PHOTO_CAP_MODE,
    MENU_PHOTO_SIZE,
    MENU_PHOTO_QUALITY,
    MENU_PHOTO_SELFTIMER,
    MENU_PHOTO_TIME_LAPSE,
    MENU_PHOTO_QUICKVIEW_DELAY,
    MENU_PHOTO_DIGITAL_ZOOM,
    MENU_PHOTO_STAMP,
#ifdef CONFIG_APP_ARD
	MENU_PHOTO_STAMP_CHOOSE,
#endif
    MENU_PHOTO_ITEM_NUM
} MENU_PHOTO_ITEM_ID_e;

typedef enum _MENU_PHOTO_MULTI_CAP_MODE_SEL_ID_e_ {
    MENU_PHOTO_MULTI_CAP_OFF = 0,
    MENU_PHOTO_MULTI_CAP_AEB,
    MENU_PHOTO_MULTI_CAP_SEL_NUM
} MENU_PHOTO_MULTI_CAP_MODE_SEL_ID_e;

typedef enum _MENU_PHOTO_NORM_CAP_MODE_SEL_ID_e_ {
    MENU_PHOTO_CAP_MODE_PRECISE = 0,
    MENU_PHOTO_CAP_MODE_PES,
    MENU_PHOTO_CAP_MODE_BURST,
    MENU_PHOTO_CAP_MODE_PRE_CAPTURE,
    MENU_PHOTO_CAP_MODE_SEL_NUM
} MENU_PHOTO_NORM_CAP_MODE_SEL_ID_e;

typedef enum _MENU_PHOTO_SIZE_SEL_ID_e_ {
    MENU_PHOTO_SIZE_1 = 0,
    MENU_PHOTO_SIZE_2,
    MENU_PHOTO_SIZE_3,
    MENU_PHOTO_SIZE_4,
    MENU_PHOTO_SIZE_5,
    MENU_PHOTO_SIZE_6,
    MENU_PHOTO_SIZE_7,
    MENU_PHOTO_SIZE_8,
    MENU_PHOTO_SIZE_9,
    MENU_PHOTO_SIZE_10,
    MENU_PHOTO_SIZE_SEL_NUM
} MENU_PHOTO_SIZE_SEL_ID_e;

typedef enum _MENU_PHOTO_QUALITY_SEL_ID_e_ {
    MENU_PHOTO_QUALITY_SFINE = 0,
    MENU_PHOTO_QUALITY_FINE,
    MENU_PHOTO_QUALITY_NORMAL,
    MENU_PHOTO_QUALITY_AUTO,
    MENU_PHOTO_QUALITY_SEL_NUM
} MENU_PHOTO_QUALITY_SEL_ID_e;

typedef enum _MENU_PHOTO_SELFTIMER_SEL_ID_e_ {
    MENU_PHOTO_SELFTIMER_OFF = 0,
    MENU_PHOTO_SELFTIMER_3S,
    MENU_PHOTO_SELFTIMER_5S,
    MENU_PHOTO_SELFTIMER_10S,
    MENU_PHOTO_SELFTIMER_SEL_NUM
} MENU_PHOTO_SELFTIMER_SEL_ID_e;

typedef enum _MENU_PHOTO_TIME_LAPSE_SEL_ID_e_ {
    MENU_PHOTO_TIME_LAPSE_OFF = 0,
    MENU_PHOTO_TIME_LAPSE_500MS,
    MENU_PHOTO_TIME_LAPSE_1S,
    MENU_PHOTO_TIME_LAPSE_5S,
    MENU_PHOTO_TIME_LAPSE_SEL_NUM
} MENU_PHOTO_TIME_LAPSE_SEL_ID_e;

typedef enum _MENU_PHOTO_QUICKVIEW_DELAY_SEL_ID_e_ {
    MENU_PHOTO_QUICKVIEW_DELAY_OFF = 0,
    MENU_PHOTO_QUICKVIEW_DELAY_1S,
    MENU_PHOTO_QUICKVIEW_DELAY_2S,
    MENU_PHOTO_QUICKVIEW_DELAY_3S,
    MENU_PHOTO_QUICKVIEW_DELAY_4S,
    MENU_PHOTO_QUICKVIEW_DELAY_5S,
    MENU_PHOTO_QUICKVIEW_DELAY_CONT,
    MENU_PHOTO_QUICKVIEW_DELAY_SEL_NUM
} MENU_PHOTO_QUICKVIEW_DELAY_SEL_ID_e;

typedef enum _MENU_PHOTO_DIGITAL_ZOOM_SEL_ID_e_ {
    MENU_PHOTO_DIGITAL_ZOOM_OFF = 0,
    MENU_PHOTO_DIGITAL_ZOOM_ON,
    MENU_PHOTO_DIGITAL_ZOOM_NUMX,
    MENU_PHOTO_DIGITAL_ZOOM_SEL_NUM
} MENU_PHOTO_DIGITAL_ZOOM_SEL_ID_e;

typedef enum _MENU_PHOTO_STAMP_SEL_ID_e_ {
    MENU_PHOTO_STAMP_OFF = 0,
    MENU_PHOTO_STAMP_DATE,
    MENU_PHOTO_STAMP_TIME,
    MENU_PHOTO_STAMP_BOTH,
    MENU_PHOTO_STAMP_SEL_NUM
} MENU_PHOTO_STAMP_SEL_ID_e;

#ifdef CONFIG_APP_ARD
enum menu_photo_stamp_choose_sel_id_e {
	MENU_PHOTO_STAMP_CHOOSE_DATE = 0,
	MENU_PHOTO_STAMP_CHOOSE_TIME,
	MENU_PHOTO_STAMP_CHOOSE_DRIVERID,
	MENU_PHOTO_STAMP_CHOOSE_NUM,
};
#endif

__END_C_PROTO__

#endif /* APP_WIDGET_MENU_PHOTO_H_ */
