ifdef CONFIG_G_SENSOR_ST_LIS3DE
libapp-objs +=peripheral_mod/g_sensor/st_lis3de/g_sensor_st_lis3de.o
endif
ifdef CONFIG_G_SENSOR_MIRA_DA380
libapp-objs +=peripheral_mod/g_sensor/mira_da380/g_sensor_mira_da380.o
endif

