
libapplib-objs +=src/utility/swscalar/ApplibUtility_SW_Scalar.o
libapplib-objs +=src/utility/swscalar/ApplibUtility_SW_Scalar_8Bit.o
libapplib-objs +=src/utility/swscalar/ApplibUtility_SW_Scalar_16Bit.o
libapplib-objs +=src/utility/swscalar/ApplibUtility_SW_Scalar_32Bit.o
