
include $(srctree)/app/cardv/app/peripheral_mod/ui/Makefile
include $(srctree)/app/cardv/app/peripheral_mod/vin/Makefile
include $(srctree)/app/cardv/app/peripheral_mod/vout/Makefile
include $(srctree)/app/cardv/app/peripheral_mod/gps/Makefile
include $(srctree)/app/cardv/app/peripheral_mod/g_sensor/Makefile
include $(srctree)/app/cardv/app/peripheral_mod/gyro/Makefile

