ifdef CONFIG_LCD_T20P52 
libapp-objs +=peripheral_mod/vout/lcd/t20p52/lcd_t20p52.o
endif

ifdef CONFIG_LCD_WDF9648W
libapp-objs +=peripheral_mod/vout/lcd/wdf9648w/lcd_wdf9648w.o
endif

ifdef CONFIG_LCD_T27P05
libapp-objs +=peripheral_mod/vout/lcd/t27p05/lcd_t27p05.o
endif

ifdef CONFIG_LCD_SSD2828
libapp-objs +=peripheral_mod/vout/lcd/ssd2828/lcd_ssd2828.o
endif
