
libapplib-objs +=src/recorder/ApplibRecorder_AudioEnc.o
libapplib-objs +=src/recorder/ApplibRecorder_ExtendEnc.o
libapplib-objs +=src/recorder/ApplibRecorder_LoopEnc.o
libapplib-objs +=src/recorder/ApplibRecorder_MemMgr.o
libapplib-objs +=src/recorder/ApplibRecorder_StillEnc.o
libapplib-objs +=src/recorder/ApplibRecorder_StillEncBurstCap.o
libapplib-objs +=src/recorder/ApplibRecorder_StillEncRawCap.o
libapplib-objs +=src/recorder/ApplibRecorder_StillEncRawEnc.o
libapplib-objs +=src/recorder/ApplibRecorder_StillEncSingleCap.o
libapplib-objs +=src/recorder/ApplibRecorder_StillEncSingleContCap.o
libapplib-objs +=src/recorder/ApplibRecorder_StillEncUtility.o
libapplib-objs +=src/recorder/ApplibRecorder_VideoEnc.o
libapplib-objs +=src/recorder/ApplibRecorder_EmptyTrackHdlr.o