

include $(srctree)/app/cardv/applib/src/player/decode_utility/Makefile
include $(srctree)/app/cardv/applib/src/player/still_decode/Makefile
include $(srctree)/app/cardv/applib/src/player/video_decode/Makefile
include $(srctree)/app/cardv/applib/src/player/audio_decode/Makefile
