
libapp-objs +=apps/gui/widget/dialog/gui_dialog.o
libapp-objs +=apps/gui/widget/menu/gui_menu.o
libapp-objs +=apps/gui/widget/menu/gui_menu_adjust.o
libapp-objs +=apps/gui/widget/menu/gui_menu_quick.o
libapp-objs +=apps/gui/widget/menu/gui_menu_time.o
libapp-objs +=apps/gui/widget/info_prompt/gui_info_prompt.o
libapp-objs +=apps/gui/widget/menu/gui_menu_adas_calib.o
libapp-objs +=apps/gui/widget/menu/gui_menu_driver_id.o
libapp-objs +=apps/gui/widget/menu/gui_menu_check_box.o
