
include $(srctree)/app/cardv/app/apps/flow/disp_param/Makefile
include $(srctree)/app/cardv/app/apps/flow/misc/Makefile
include $(srctree)/app/cardv/app/apps/flow/pb/Makefile
include $(srctree)/app/cardv/app/apps/flow/rec/Makefile
include $(srctree)/app/cardv/app/apps/flow/thumb/Makefile
include $(srctree)/app/cardv/app/apps/flow/usb/Makefile
include $(srctree)/app/cardv/app/apps/flow/widget/Makefile
include $(srctree)/app/cardv/app/apps/flow/sound/Makefile
