

include $(srctree)/app/cardv/applib/src/calibration/blc/Makefile
include $(srctree)/app/cardv/applib/src/calibration/bpc/Makefile
include $(srctree)/app/cardv/applib/src/calibration/ca/Makefile
include $(srctree)/app/cardv/applib/src/calibration/vig/Makefile
include $(srctree)/app/cardv/applib/src/calibration/warp/Makefile
include $(srctree)/app/cardv/applib/src/calibration/wb/Makefile
include $(srctree)/app/cardv/applib/src/calibration/adjust/Makefile
libapplib-objs +=src/calibration/ApplibCalib.o
libapplib-objs +=src/calibration/ApplibCalibCli.o
libapplib-objs +=src/calibration/ApplibCalibMgr.o
libapplib-objs +=src/calibration/ApplibCalibVar.o
